language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - PIP_USE_MIRRORS=true
install:
  - pip install .
  - pip install nose mock
script: nosetests
notifications:
  email: false
